# Generated by Django 3.2.8 on 2021-10-23 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_conversation_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.operator', blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='resolved_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='operator',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
